config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about',as:'about'
  get '/book/top' =>'books#top'
  resources :books, only: [:index, :show, :new, :create,:edit,:destroy,:update]
  resources :users, only: [:show, :edit,:index,:create,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  

    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }
end


  

app/models/postimage.rb
class Postimage < ApplicationRecord
     has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
       
        has_many :books, dependent: :destroy
        has_one_attached :profile_image
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top,:about]
      before_action :configure_permitted_parameters, if: :devise_controller?
      
def after_sign_in_path_for(resource)
  user_path(current_user.id)
end



  
  def after_sign_out_path_for(resource)
   root_path
    
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def top
    @books = Book.all
    @book = Book.new
    @user = current_user
    
  end

  def new
  @book = Book.new
  render partial: "User_info/new_books", locals: { book: @book }
  end
  
  def book
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books =Book.all
      render :index
    end
  end
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end
  
  
def show
  @book_new = Book.new
  @book = Book.find(params[:id])
  @user = @book.user
end
  
  def edit
  @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      
      render :edit
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to book  
  end
  
  private
    def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end


  def book_params
    params.require(:book).permit(:title, :body, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @book=Book.new
    @user = current_user
    @books = Book.all
  end

  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @user = User.new
    @book = Book.new
  end  
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Book was successfully created."
      redirect_to @user
    else
      @user = User.all
      render :index
    end
  end
  
def index

  @users = User.all
  @book = Book.new
  if user_signed_in?
    @user = current_user
    @books = @users.all
  end
  @users = User.all
end
 
def show
  @book = Book.new
  @user = User.find(params[:id])
  @books = @user.books
  @introduction = @user.introduction
  @users = User.all
end

  def edit
    @user = User.find(params[:id])
  unless @user.id == current_user.id
    redirect_to books_path(current_user)
  end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/User_info/_new_books.html.erb
<h3>New book</h3>
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <%= book.errors.count %> errors prohibited this obj from being saved:
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", placeholder: "Body" %>
  </div>
  <%= form.submit "Create Book", class: "btn btn-success" %>
<% end %>

app/views/User_info/_user_info.html.erb
<h2>User Info</h2>
<table class="table">
  <tbody><tr></tr>
  <tr>
 <%= image_tag user.get_profile_image(100,100) %>
  <th>name</th>
  <th><%= user.name %></th>
  </tr>
  <tr>
  <th>introduction</th>
  <th><%= user.introduction %></th>
	  <th></th>
  </tr>
</tbody></table>

  
<li class="nav-item">
 <%= link_to  edit_user_path(user),class:"btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<%end%>
</li>

app/views/books/edit.html.erb
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <p><%= f.submit 'Update Book', url: book_path(@book), method: :put,class: "btn btn-sm btn-success" %></p>
<td><%= link_to 'Show', book_path(@book.id) %></td>
<tb>|</tb>
<td><%= link_to 'Back', books_path %></td>
<%end%>
  </div>
</div>
      </div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
　　<tr></tr>
  　　<tr>
　　　　<%= render 'User_info/user_info', user: @user %>
　　　　<%= render 'User_info/new_books', book: @book %>
	  　　<th></th>
  　　</tr>
   </div>
　　　<div class="col-md-8 offset-md-1">
      　<h2>Books</h2>
  　　　<table class="table">
  　　<thead>
    <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  　　</thead>
<tbody>
<% @books.each do |book| %>
  <tr>
    <td>
      <%= link_to user_path(book.user) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <% end %>
    </td>
    
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>
</div>
</div>

      
      

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0" >
<div class="row">
<div class="col-md-3">
<td><%= render 'User_info/user_info', user: @user %></td>
<td><%= render 'User_info/new_books', book: @book_new %></td>
</div> 
<div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
<table class="table">
<tbody>
<tr>
<td>
  <%= link_to user_path(@user) do %>
    <%= image_tag @book.user.get_profile_image(100, 100) %></br>
    <%= @user.name %>
  <% end %>
</td>
        <td><%= @book.title %></td>
        <td><%= @book.body %></td>
        <% if @book.user == current_user %>
        <td> <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' },class: "btn btn-sm btn-danger" %></td>
        <%end%>
        </tr>
  </tbody>
  </table>
</div>
</div>
</div>

app/views/homes/about.html.erb
  <p id="notice"></p>
  <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
     　　<h1>welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></h1>
      </div>
    </div>
  </div>

app/views/homes/top.html.erb
  <p id="notice"></p>
  <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
     　　<h1>welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></h1>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
   <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
   
 
<body>
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          
<li>
<% if user_signed_in? %>

<li class="nav-item">

<%= link_to user_path(current_user), class:"nav-link text-light" do %>  
<i class="fas fa-home"></i>Home
  <%end%>   
</li>

<li class="nav-item">
<%= link_to users_path, class:"nav-link text-light" do %>  
<i class="fas fa-users"></i>Users
<%end%>  
</li>

<li class="nav-item">
<%= link_to "/books", class:"nav-link text-light" do %> 
<i class="fas fa-book-open"></i>Books
<%end%>
</li>

<li class="nav-item">
<%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
<i class="fas fa-sign-out-alt"></i>Log out
<%end%>
</li>
<% else %>
<li>
<%= link_to  root_path, class:"nav-link text-light" do %>  
<i class="fas fa-home"></i>Home
<%end%>   
</li>
              
<li class="nav-item">
<%= link_to about_path, class:"nav-link text-light" do %>
<i class="fas fa-link"></i>About
<%end%>
</li>
             
<li class="nav-item">
<%= link_to "/users/sign_up", class:"nav-link text-light" do %>
<i class="fas fa-user-plus"></i>Sign up
<%end%>
</li>
            
<li class="nav-item">
<%= link_to "/users/sign_in", class:"nav-link text-light" do %>
<i class="fas fa-sign-in-alt"></i>Log in
<%end%>
</li>
<%end%>


        </ul>
      </div>
    </div>
  </nav>

</header>

      <main>

<% flash.each do |message_type, message| %>

<div class="alert alert-<%= message_type %>"><%= message %></div> 
<%end%>
  <%= yield %>
      </main>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  

</body>

</html>

app/views/user/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/edit.html.erb
<p id="notice"></p>
  <div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <tr> <%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
   <p> <%= f.text_field :name, autofocus: true, placeholder:"名前"%></p>
   
   
  <label for="inputImage">Image</label>
 <p> <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  </p>
 
   <label for="caption">Introduction</label>
   <p> <%= f.text_field :introduction %></p>
   <%= f.submit "Update User", class:"btn btn-secondary" %>
   
<% end %>
</tr>
</div>
</div>
</div>

app/views/users/index.html.erb
        <p id="notice"></p>
        <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

<%= render 'User_info/user_info', user: @user %>
<%= render 'User_info/new_books', book: @book %>
	 
　<div class="form-group">
    
  </div>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
        <% @users.each do |user| %>
    <tr>
    <td><%= image_tag user.get_profile_image(100,100) %></td>
    <td><%= user.name %></td>
    <td><%= link_to 'Show',  user_path(user) %></td>
     <% end %>
     </tr>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<body>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
<td><%= render 'User_info/user_info', user: @user %></td>
<td><%= render 'User_info/new_books', book: @book %></td>
  </div>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
<% @books.each do |book| %>
  <tr>
<td>
  <%= image_tag book.user.get_profile_image(100,100) %></br>
  <%= link_to @user.name,user_path(@user) %>
</td>
<td><%= link_to book.title, book_path(book.id) %></td>
<td><%= book.body %></td>
 </tr>
<% end %>
</tbody>
</table>
 </div>
 </div>
 </body>